export type TransactionType =
	| "CREATE_CARD"
	| "AUTHORISATION"
	| "SETTLEMENT"
	| "REVERSAL"
	| "DEPOSIT"
	| "FUND_CARD"
	| "PURCHASE"
	| "REFUND"
	| "SWEEP"
	| "CLOSE"
	| "FREEZE"
	| "THAW"
	| "APPROVAL_PENDING"
	| "EXPIRE"
	| "UNKNOWN"
