name: Build & Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ runner.os }}-cache
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Update NPM
        run: npm install -g npm
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        env:
          url: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        run: npm run test
