name: "Publish"

on:
  push:
    tags:
      - "release-*"

jobs:
  publish:
    name: "Publish from master"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"

      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version: 20
          # Setting the registry-url here tells the action to automatically 
          # generate a correct .npmrc for you.
          registry-url: 'https://registry.npmjs.org'
          # Explicitly setting the scope ensures the token is mapped to @pax2pay
          scope: '@pax2pay'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        # We use the built-in NODE_AUTH_TOKEN variable which setup-node 
        # specifically looks for to authenticate the publish.
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
